### ISSUE TITLE
v1.0.0 (next)

### ISSUE THREAD

**Issue by serapath** [wizardamigos/profiles#5]
http://wizardamigos.com/profiles/

## TODOs for `version 1.0.0`
(if you want to work on an issue - just got to the issue and **`assign`** it to you :+1: 

* [ ] profiles page concept https://github.com/wizardamigos/profiles/issues/6 
    * [ ] responsive layout of many profile cards https://github.com/wizardamigos/profiles/issues/14
    * [ ] retrieve `config.json` data from github profiles https://github.com/wizardamigos/profiles/issues/9 @kiecoo 
* [ ] search & filter bar visual interaction concept https://github.com/wizardamigos/profiles/issues/7 @jameslin3263
    * [ ] search & filter bar javascript logic https://github.com/wizardamigos/profiles/issues/10 @jameslin3263
* [ ] profile card https://github.com/wizardamigos/profiles/issues/8 @Yugalitree @TzuYuanLiu 
    * [ ] user recent activity feed https://github.com/wizardamigos/profiles/issues/12
    * [ ] add user private gitter message chat https://github.com/wizardamigos/profiles/issues/13 @kiecoo
* [ ] user card gallery [feature] animated card gallery component
  * [ ] https://github.com/wizardamigos/profiles/issues/15 @jameslin @tzuyuan

**Comment by Yugalitree** [comment]
Currently there are chat room box area and all members name of codecamp.
I have a idea to improve the layout which could recognize everyone more easily. ( maybe add everyone's photo or other methods. )  
And create a group view to see everyone in which group and do what project now.

**Comment by EnochMbaebie** [comment]
Thats' cool

**Comment by kiecoo** [comment]
To Alex
1. the html & css that I did  
https://codepen.io/kiecoo/pen/aEJLbm
2. my AMA
https://github.com/kiecoo/profiles/issues/1
3. csjs & bel: I remember (I could update the new one now)

**Comment by serapath** [comment]
@EnochMbaebie 
do you also have a link or a summary of what you already did with js/html/css?

@kiecoo 
do you still remember how to do that codepen with `csjs` and `bel` in javascript without a seperate html or css file?

@Yugalitree 
this is a good idea - can you also write (you can also edit your comment above) - to add if you already know some basics about html, css and/or javascript? :-)

**If you are ready - just join me here to discuss more details now**
# https://meet.jit.si/wizardamigos


# @Yugalitree @EnochMbaebie @kiecoo , please click the link above now - i'm waiting :-)

**Comment by kiecoo** [comment]
@serapath 

- my AMA
https://github.com/kiecoo/profiles/issues/1

- csjs & bel: I remember (I could update the new one now)

**Comment by dineshmaxi-web** [comment]
i am interested in doing this.
i finished 6 projects in fcc

**Comment by serapath** [comment]
@EnochMbaebie @1532j0004kg did you already do the portfolio and/or quiz app?
We meet tomorrow again - if you manage to be online, join us :-)

In the mean time you can check this to practice:
* https://esova-ana.github.io/portfolio/
* https://github.com/esova-ana/portfolio/blob/gh-pages/index.js
* https://www.youtube.com/playlist?list=PLbtP2pUMT_hvANJ-b49tp88sOkVLSOkcq

**Comment by dineshmaxi-web** [comment]
yes i did the the portfolio already(not more effective), but i know how to construct & to code.

**Comment by 1532j0004kg** [comment]
not more effective but i know how to construct & to code

**Comment by serapath** [comment]
ok cool :-) awesome. that will be cool. maybe you can even help with some more advanced stuff - but the advanced stuff has less design and more coding aspects. https://github.com/wizardamigos/profiles/issues/9
